### GENERAL SETTINGS ###

# Site settings
title: UNDERDOG SECURITY
description: "Underdog Security is a UK based cybersecurity consultancy firm specializing in penetration testing, secure code review and social engineering."
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "" #important: start with /
url: "http://underdog-security.github.io"

# Build settings
markdown: kramdown
permalink: /:categories/:title/
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#00b3fe" #"#F70031"
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"

# Making projects separate from posts
collections:
  projects:
    output: true
    permalink: /projects/:title/
  questions:
    output: true
    permalink: /questions/:title/

### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: twitter
    url: https://twitter.com/UDSec_UK

# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines:
    - 71-75 Shelton Street,
    - WC2H 9JQ, London,
    - United Kingdom
email: info@underdogsecurity.com


### GENERAL DATA FOR VARIOUS LOCATIONS ###

# Members information. Shown on About page.
members:
  - name: Daley Bee
    position: Director
    text: Daley is an experienced security researcher and penetration tester with a main focus on web application security, exploit development and open source intelligence. 
    img: 
    social:
      - title: envelope #use for email address
        url: mailto:daley@underdogsecurity.com
      - title: twitter
        url: https://twitter.com/daley
  - name: Dominik Penner
    position: Director
    text: purus viverra accumsan in nisl nisi scelerisque eu ultrices vitae auctor eu augue ut lectus arcu bibendum at varius vel pharetra vel turpis nunc eget lorem dolor sed viverra ipsum nunc aliquet  
    img: 
    social:
      - title: envelope #use for email address
        url: mailto:dominik@underdogsecurity.com
      - title: twitter
        url: https://twitter.com/zer0pwn
  - name: Jake Bolam
    position: Director
    text: purus viverra accumsan in nisl nisi scelerisque eu ultrices vitae auctor eu augue ut lectus arcu bibendum at varius vel pharetra vel turpis nunc eget lorem dolor sed viverra ipsum nunc aliquet
    img: 
    social:
      - title: envelope #use for email address
        url: mailto:jake@underdogsecurity.com
      - title: twitter
        url: https://twitter.com/jake_sec
  - name: Timothy French
    position: Director
    text: purus viverra accumsan in nisl nisi scelerisque eu ultrices vitae auctor eu augue ut lectus arcu bibendum at varius vel pharetra vel turpis nunc eget lorem dolor sed viverra ipsum nunc aliquet
    img: 
    social:
      - title: envelope #use for email address
        url: mailto:timothy@underdogsecurity.com
      - title: twitter
        url: https://twitter.com/leet_sauce

# Clients information. Shown on Home and About pages.
clients:
  - name: dribbble
    img: client01.png
  - name: Code is Poetry
    img: client02.png
  - name: Vimeo
    img: client03.png
  - name: VimeoPro
    img: client04.png

# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "Underdog Security is a UK based cybersecurity consultancy firm specializing in penetration testing, secure code review and social engineering."

# Testimonial content. Shown on Home and About page.
testimonial:
    message: "I’ve personally known several of the researchers that work at Underdog Security and I can confidently say they are some of the most talented individuals I have ever worked with. The sheer amount of skill possessed by this group is unrivalled and they consistently demonstrate it with the research they publish. Happy to provide any further reference for UnderdogSec if needed."
    author: Manny Mand
    position: Cybersecurity Instructor - University of Toronto
